day37/homework/project/myApp/urls.py
from django.conf.urls import url

from . import views
urlpatterns = [
    url(r'^$', views.index),

    url(r'^base/$', views.base),
    url(r'^baseindex/$', views.baseindex, name='baseindex'),
    url(r'^base1/$', views.base1),
    url(r'^detail/$', views.detail, name='detail'),
    url(r'^usercenter/$', views.usercenter, name='usercenter'),
    url(r'^shoppingcar/$', views.shoppingcar, name='shoppingcar'),
    url(r'^login/$', views.login, name='login'),
    url(r'^verifycode/$', views.verifycode, name='verifycode'),
    url(r'^verifycodefile/$', views.verifycodefile),
    url(r'^verifycodecheck/$', views.verifycodecheck),
]

day37/homework/project/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('myApp.urls',namespace='app'))
]

day37/homework/project/myApp/models.py
from django.db import models

# Create your models here.
class Grades(models.Model):
    gname    = models.CharField(max_length=20)
    gdate    = models.DateTimeField()
    ggirlnum = models.IntegerField()
    gboynum  = models.IntegerField()
    isDelete = models.BooleanField(default=False)
    def __str__(self):
        return self.gname

class Students(models.Model):
    sname    = models.CharField(max_length=20)
    sgender  = models.BooleanField(default=True)
    sage     = models.IntegerField()
    scontend = models.CharField(max_length=20)
    isDelete = models.BooleanField(default=False)
    # 关联外键
    sgrade = models.ForeignKey("Grades")
    def __str__(self):
        return self.sname

day37/homework/project/myApp/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
def index(request):
    return HttpResponse("sunck is a good man")
    # return render(request,'myApp/index.html')
    # return HttpResponse("<h1>sunck is a good man</h1>")
# 父模板
def base(request):
    return render(request, 'myApp/base.html')
def base1(request):
    return render(request, 'myApp/base1.html')
def baseindex(request):
    return render(request, 'myApp/baseindex.html')
def detail(request):
    return render(request, 'myApp/detail.html')
def usercenter(request):
    return render(request, 'myApp/usercenter.html')
def shoppingcar(request):
    return render(request, 'myApp/shoppingcar.html')
def login(request):
    return render(request, 'myApp/login.html')

def verifycode(request):
    # 引入绘图模块
    from PIL import Image, ImageDraw, ImageFont
    # 引入随机函数模块
    import random
    # 定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20, 100), random.randrange(
        20, 100), random.randrange(20, 100))
    width = 100
    height = 50
    # 创建画面对象
    im = Image.new('RGB', (width, height), bgcolor)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)
    # 调用画笔的point()函数绘制噪点
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    # 定义验证码的备选值
    str = '1234567890QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm'
    # 随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str[random.randrange(0, len(str))]
    # 构造字体对象
    font = ImageFont.truetype(r'C:\Windows\Fonts\AdobeArabic-Bold.otf', 40)
    # 构造字体颜色
    fontcolor1 = (255, random.randrange(0, 255), random.randrange(0, 255))
    fontcolor2 = (255, random.randrange(0, 255), random.randrange(0, 255))
    fontcolor3 = (255, random.randrange(0, 255), random.randrange(0, 255))
    fontcolor4 = (255, random.randrange(0, 255), random.randrange(0, 255))

    # 绘制4个字
    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor1)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor2)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor3)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor4)
    # 释放画笔
    del draw
    # 存入session，用于做进一步验证
    request.session['verify'] = rand_str
    # 内存文件操作
    import io
    buf = io.BytesIO()
    # 将图片保存在内存中，文件类型为png
    im.save(buf, 'png')
    # 将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(buf.getvalue(), 'img/png')

def verifycodefile(request):
    f = request.session.get('flag', True)
    str = ""
    if f == False:
        str = "请重新输入"
    request.session.clear()
    return render(request, 'myApp/verifycodefile.html',{'flag': str})
from django.shortcuts import redirect
def verifycodecheck(request):
    code1 = request.POST.get('verifycode').upper()
    code2 = request.session['verify'].upper()
    if code1 == code2:
        return render(request, 'myApp/success.html')
    else:
        request.session['flag'] = False
        return redirect('/sunck/verifycodefile')

day37/homework/project/templates/myApp/base.html
<!DOCTYPE html>
<html>
	<head>
        {% load staticfiles %}
		<meta charset="utf-8" />
		<script src="{% static 'myApp/js/jquery-3.1.1.min.js' %}"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'myApp/css/bootstrap.min.css' %}"/>
   	 	<script src="{% static 'myApp/js/bootstrap.min.js' %}"></script>

		<link rel="icon" href="{% static 'myApp/img/small.jpg' %}" type="image/x-icon"/>
		<title>爱鲜蜂 - 各种新鲜 闪电送达</title>
		<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" />
		<style type="text/css">
			*{
				margin: 0px;
				padding: 0px;
			}
			nav{
				width: 100%;
				height: 59px;
				line-height: 59px;
				text-align: center;
				background-color: #FFD600;
				position: fixed;
				left: 0;
				top: 0;
				display: flex;
			}
			nav h3{
				flex-grow: 1;
			}
			footer{
				width: 100%;
				height: 59px;
				line-height: 59px;
				text-align: center;
				background-color: #F6F6F6;
				position: fixed;
				left: 0;
				bottom: 0;
			}
			footer ul{
				list-style: none;
				display: flex;
			}
			footer ul li{
				width: 100px;
				line-height: 59px;
			}
			footer ul li a{
				display: block;
				height: 59px;

			}
			footer ul li a:active{
				color: black;
				background-color: #FFD600;
			}
			#main{
				/*width: 49px;*/
				margin-top: 59px;
				margin-bottom: 57px;
				padding-bottom:15px;
				display:flex;
				flex-direction:column;
				background-color: #EFEFEF;
			}
			a{
			    color: #A2A2A2;
				text-decoration: none;
			}
			a:active{
				text-decoration: none;
			}
		</style>

	</head>
	<body>
		<nav>
			<h3>
                {% block h3 %}

                {% endblock %}
            </h3>
		</nav>
		<div id="main">
			{% block main %}

            {% endblock %}
		</div>
		<footer>
			<ul>
				<li><a href="{% url 'app:baseindex' %}">首页</a></li>
				<li><a href="{% url 'app:detail' %}">闪送超市</a></li>
				<li><a href="{% url 'app:shoppingcar' %}">购物车</a></li>
				<li><a href="{% url 'app:usercenter' %}">我的</a></li>
			</ul>
		</footer>
	</body>
</html>

day37/homework/project/templates/myApp/base1.html
{% extends 'myApp/base.html' %}

{% block main %}
    <style>
        #main1{
            display:flex;
			flex-direction:row;
        }
        #mainleft{
            <!--float:left:-->
            height:800px;
            background-color:#F5F5F5;
            flex-grow:1;
        }
        #mainright{
            <!--float:left:-->
            width:400px;
            height:800px;
            background-color:white;
            flex-grow:5;
        }
        #mainleft li{
            width:1 rem;
            line-height:65px;
            text-align:center;
            border-bottom:1px solid #E0E0E0;
        }
    </style>
    <div id="main1">
        <div id="mainleft">
            {% block mainleft %}

            {% endblock %}
        </div>
        <div id="mainright">
            {% block mainright %}

            {% endblock %}
        </div>
    </div>

{% endblock %}

day37/homework/project/templates/myApp/detail.html
{% extends 'myApp/base1.html' %}

{% block h3 %}
    详情页
{% endblock %}

{% block mainleft %}
         <ul>
             <li><a href="#">热销新品</a></li>
             <li><a href="#">优选水果</a></li>
             <li><a href="#">卤味熟食</a></li>
             <li><a href="#">牛奶面包</a></li>
             <li><a href="#">冰镇饮料</a></li>
             <li><a href="#">冰激凌</a></li>
             <li><a href="#">饮料酒水</a></li>
             <li><a href="#">休闲零食</a></li>
             <li><a href="#">方便速食</a></li>
             <li><a href="#">粮油调味</a></li>
        </ul>
{% endblock %}

{% block mainright %}

{% endblock %}

day37/homework/project/templates/myApp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    <h1>yang is happy</h1>
</body>
</html>

day37/homework/project/templates/myApp/login.html
{% extends 'myApp/base.html' %}

{% block h3 %}
    登录
{% endblock %}

{% block main %}
    {% load static from staticfiles %}
    <style>
        #login1{
            height:465px;
            margin:30px 20px;
        }
    </style>
    <div id="login1">
        <form class="form-horizontal" >
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">用户名</label>
                <div class="col-sm-10">
                    <input type="email" class="form-control" id="inputEmail3" placeholder="Username">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-2 control-label">密码</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-2 control-label">验证码</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="inputPassword" placeholder="Check">
                </div>
                <div class="col-sm-10">
                    <img src=""/>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox"> 记住密码
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">登录</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

day37/homework/project/templates/myApp/shoppingcar.html
{% extends 'myApp/base.html' %}

{% block h3 %}
    <style>
        h3{
            height:100%;
            padding-top: 17px;
            margin:0;
            background-color:#f9fafd;
        }
    </style>
    购物车
{% endblock %}

{% block main %}
    {% load static from staticfiles %}
    <style>
        #main{
            height:535px;
        }

    </style>
    <link rel="stylesheet" href="{% static 'myApp/css/caranduser.css' %}"/>
    <div id="car">
        <div id="tubiao">
            <img src="{% static 'myApp/img/empty_addrlist-7b6725e9.png' %}" width="27%" height="100%"/>
        </div>
        <div id="kongkong">
            亲，购物车空空的耶~
        </div>
        <div id="quguang">
            <a href="{% url 'app:baseindex' %}">去逛逛</a>
        </div>
    </div>
{% endblock %}

day37/homework/project/templates/myApp/usercenter.html
{% extends 'myApp/base1.html' %}

{% block h3 %}
    用户中心
{% endblock %}

{% block mainleft %}
    <ul>
        <li><a href="#">个人信息</a></li>
        <li><a href="#">登录</a></li>
        <li><a href="#">注册</a></li>
        <li><a href="#">我的</a></li>
        <li><a href="#">关于我们</a></li>
    </ul>
{% endblock %}

{% block mainright %}
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'myApp/css/caranduser.css' %}"/>
    <div id="car">
        <div id="tubiao">
            <img src="{% static 'myApp/img/cmy.png' %}" width="27%" height="100%"/>
        </div>
        <div id="kongkong">
            亲，您还没有登录哦~
        </div>
        <div id="quguang">
            <a href="{% url 'app:login' %}">去登录</a>
        </div>
    </div>
{% endblock %}