day37/kaiye/project/myApp/urls.py
from django.conf.urls import url

from . import views
urlpatterns = [
    url(r'^$', views.index),
    url(r'^students/$', views.students),
    url(r'^good/(\d+)$', views.good, name='good'),

    url(r'^main/$', views.main),
    url(r'^postfile/$', views.postfile),
    url(r'^showinfo/$', views.showinfo),

    url(r'^verifycode/$', views.verifycode),
    url(r'^verifycodefile/$', views.verifycodefile),
    url(r'^verifycodecheck/$', views.verifycodecheck),
]

day37/kaiye/project/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^sunck/', include('myApp.urls', namespace='app'))
]

day37/kaiye/project/myApp/models.py
from django.db import models

# Create your models here.
class Grades(models.Model):
    gname    = models.CharField(max_length=20)
    gdate    = models.DateTimeField()
    ggirlnum = models.IntegerField()
    gboynum  = models.IntegerField()
    isDelete = models.BooleanField(default=False)
    def __str__(self):
        return self.gname

class Students(models.Model):
    sname    = models.CharField(max_length=20)
    sgender  = models.BooleanField(default=True)
    sage     = models.IntegerField()
    scontend = models.CharField(max_length=20)
    isDelete = models.BooleanField(default=False)
    # 关联外键
    sgrade = models.ForeignKey("Grades")
    def __str__(self):
        return self.sname
    def getName(self):
        return self.sname

day37/kaiye/project/myApp/views.py
from django.shortcuts import render

# Create your views here.

from .models import Students
from django.http import HttpResponse
def index(request):
    # return HttpResponse("sunck is a good man")
    stu = Students.objects.get(pk = 1)
    return render(request,'myApp/index.html', {'stu':stu, "num" : 10,
                                               'str': 'sunck is a nice ',
                                               'list': ['good', 'nice', 'cute'],
                                               'test': False,
                                               'code': '<h1>yang is happy</h1>'})

def students(request):
    students = Students.objects.all()
    return render(request, 'myApp/students.html',{'studentslist': students})

def good(request, page):
    return render(request, 'myApp/good.html', {'num': page})

def main(request):
    return render(request, 'myApp/main.html')

def postfile(request):
    return render(request, 'myApp/postfile.html')
def showinfo(request):
    name = request.POST.get('username')
    pwd = request.POST.get('password')
    return render(request, 'myApp/showinfo.html', {"username": name,
                                                   "password": pwd})


def verifycode(request):
    # 引入绘图模块
    from PIL import Image, ImageDraw, ImageFont
    # 引入随机函数模块
    import random
    # 定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20, 100), random.randrange(
        20, 100), random.randrange(20, 100))
    width = 100
    height = 50
    # 创建画面对象
    im = Image.new('RGB', (width, height), bgcolor)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)
    # 调用画笔的point()函数绘制噪点
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    # 定义验证码的备选值
    str = '1234567890QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm'
    # 随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str[random.randrange(0, len(str))]
    # 构造字体对象
    font = ImageFont.truetype(r'C:\Windows\Fonts\AdobeArabic-Bold.otf', 40)
    # 构造字体颜色
    fontcolor1 = (255, random.randrange(0, 255), random.randrange(0, 255))
    fontcolor2 = (255, random.randrange(0, 255), random.randrange(0, 255))
    fontcolor3 = (255, random.randrange(0, 255), random.randrange(0, 255))
    fontcolor4 = (255, random.randrange(0, 255), random.randrange(0, 255))

    # 绘制4个字
    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor1)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor2)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor3)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor4)
    # 释放画笔
    del draw
    # 存入session，用于做进一步验证
    request.session['verify'] = rand_str
    # 内存文件操作
    import io
    buf = io.BytesIO()
    # 将图片保存在内存中，文件类型为png
    im.save(buf, 'png')
    # 将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(buf.getvalue(), 'img/png')

def verifycodefile(request):
    f = request.session.get('flag', True)
    str = ""
    if f == False:
        str = "请重新输入"
    request.session.clear()
    return render(request, 'myApp/verifycodefile.html',{'flag': str})
from django.shortcuts import redirect
def verifycodecheck(request):
    code1 = request.POST.get('verifycode').upper()
    code2 = request.session['verify'].upper()
    if code1 == code2:
        return render(request, 'myApp/success.html')
    else:
        request.session['flag'] = False
        return redirect('/sunck/verifycodefile')

day37/kaiye/project/templates/myApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        #header{
            width:100%;
            height:100px;
            background-color:red;
        }
        #footer{
            width:100%;
            height:100px;
            background-color:pink;
        }

    </style>
</head>
<body>
    <div id="header">header</div>

    <div id="main">
        {% block main %}

        {% endblock main %}
        <hr />
        {% block main2 %}

        {% endblock main2 %}
    </div>

    <div id="footer">footer</div>
</body>
</html>

day37/kaiye/project/templates/myApp/good.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>good页面</title>
</head>
<body>
<h1>good页面 -- {{num}}</h1>
</body>
</html>

day37/kaiye/project/templates/myApp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    <a href="/sunck/good/">链接</a>
    <a href="{% url 'app:good' 1 %}">url链接</a>

    <h1>sunck is a good man</h1>
    <h1>{{stu.sname}}</h1>
    <h1>{{stu.getName}}</h1>
    <h2>num = *{{num}}*</h2>
    {% if num %}
        <h1>sunck is a good man</h1>
    {% endif%}

    <!--注释-->
    {% comment %}
        <h1>sunck is a good man</h1>
        <h1>{{stu.sname}}</h1>
        <h1>{{stu.getName}}</h1>
    {% endcomment %}

    {% ifequal 'sunck' 'sunck' %}
        欢迎光临
    {% endifequal %}

    <h1>{{str|upper}}</h1>
    <h1>{{str}}</h1>

    <h1>{{list|join:'#'}}</h1>

    <h1>{{test|default:'没有'}}</h1>

    <h2>*{{num}}*</h2>
    <h2> *{{num|add:10}}*</h2>
    <h2>*{{num|add:-5}}*</h2>
    <!--{% comment %}-->
    <!--num/1*5-->
    <h2>*{{ widthratio num 1 5}}*</h2>
    <!--num/5-->
    <h2>*{{ widthratio num 5 1}}*</h2>
     <!--{% endcomment %}-->

    {{code}}
    {{code|escape}}
    {{code|safe}}   <!--转义成功-->
    {% autoescape off %}
        自动转义：{{code}}
    {% endautoescape %}
</body>
</html>

day37/kaiye/project/templates/myApp/main.html
{% extends 'myApp/base.html' %}

{% block main %}
    <h1>sunck is a good man</h1>
{% endblock main %}

{% block main2 %}
    <h1>kaige is a good man</h1>
{% endblock main2 %}

day37/kaiye/project/templates/myApp/postfile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>表单提交</title>
</head>
<body>
    <form action="/sunck/showinfo/" method="post">
        {% csrf_token %}
        姓名：<input type="text" name="username"/>
        <hr />
        密码：<input type="password" name="password">
        <hr />
        <input type="submit" value="登录"/>
    </form>
</body>
</html>

day37/kaiye/project/templates/myApp/showinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>展示信息</title>
</head>
<body>
    <h1>username:{{username}}</h1>
    <h1>password:{{password}}</h1>
</body>
</html>

day37/kaiye/project/templates/myApp/students.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学生列表</title>
</head>
<body>
    <h1>学生列表</h1>

    <ul>
        {% for stu in studentslist %}
            {% if forloop.counter|divisibleby:2 %}
                <li style="color:red;">
                    {{forloop.counter}}--{{stu.sname}}--{{stu.sgrade}}
                </li>
            {% else %}
                <li>
                {{forloop.counter}}--{{stu.sname}}--{{stu.sgrade}}
                </li>
            {% endif %}
        {% empty %}
            <li>目前没有学生</li>
        {% endfor %}
    </ul>
</body>
</html>

day37/kaiye/project/templates/myApp/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登陆成功</title>
</head>
<body>
    <h1>恭喜你，登陆成功。。。。。。</h1>
</body>
</html>

day37/kaiye/project/templates/myApp/verifycodefile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post" action="/sunck/verifycodecheck/">
        {% csrf_token %}
        <input type="text" name="verifycode" />
        <img src="/sunck/verifycode/">
        <input type="submit" value="登录" />
        <span>{{flag}}</span>
    </form>
</body>
</html>